[tool.poetry]
name = "dbscripts"
version = "1.3.1"
description = "Collection of helper scripts for postgresql"
authors = ["David Nugent <davidn@uniquode.io>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Topic :: Database :: Front-Ends",
    "Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = "^3.9"
envex = "^1.5.0"
psycopg = {extras = ["binary"], version = "^3.1.8"}

[project.scripts]
dbcreate = "dbscripts.dbcreate:main"
dbready = "dbscripts.dbready:main"

[tool.poetry.group.dev.dependencies]
pytest = ">= 7.2"
pytest-django = "^4.5.2"
django-debug-toolbar = "^4.1.0"
coverage = "^7.2.5"
pre-commit = "^3.3.3"
black = "^23.7.0"
ruff = "^0.0.285"
isort = "^5.12.0"

[tool.pytest.ini_options]
minversion = "7.2"
addopts = "-ra -q --reuse-db"
pythonpath = "app"
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = [
    "**/tests/*"
]

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
