[tool.poetry]
name = "dbscripts"
version = "1.5.0"
description = "Collection of helper scripts for postgresql"
authors = ["David Nugent <davidn@uniquode.io>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Topic :: Database :: Front-Ends",
    "Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = ">=3.10.0,<4.0.0"
envex = ">=3.0.3"
psycopg = {extras = ["binary"], version = ">=3.1.8"}

[tool.poetry.scripts]
dbcreate = "dbscripts.dbcreate:main"
dbready = "dbscripts.dbready:main"

[tool.poetry.group.dev.dependencies]
pytest = ">= 7.2"
pre-commit = "^3.3.3"
ruff = "^0.4.10"
testcontainers = "^4.4.0"
black = "24.4.2"

[tool.ruff]
namespace-packages = ["dbscripts"]

[tool.pytest.ini_options]
minversion = "7.2"
addopts = "-ra -q"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
