[tool.poetry]
name = "dbscripts"
version = "1.1.0"
description = "Collection of helper scripts for postgresql"
authors = ["David Nugent <davidn@uniquode.io>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Topic :: Database :: Front-Ends",
    "Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = "^3.8"
envex = "^1.5.0"
psycopg2-binary = ">=2.9"

[tool.poetry.scripts]
dbcreate = "dbscripts.dbcreate:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
