[tool.poetry]
name = "dbscripts"
version = "1.0.0"
description = "Collection of helper scripts for postgresql"
authors = ["David Nugent <davidn@uniquode.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
envex = "^1.5.0"
psycopg2-binary = "^2.9.5"

[tool.poetry.scripts]
devtest = { callable = "scripts:dbcreate.py" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
