[tool.poetry]
name = "dbscripts"
version = "1.2.0"
description = "Collection of helper scripts for postgresql"
authors = ["David Nugent <davidn@uniquode.io>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Topic :: Database :: Front-Ends",
    "Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
envex = ">=1.5.0"
psycopg = {extras = ["binary"], version = "^3.1.8"}

[tool.poetry.scripts]
dbcreate = "dbscripts.dbcreate:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
