name: build

on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13" , "3.12", "3.11" ]

    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch all tags
        fetch-depth: 0

    - uses: deeprave/test-build@v1
      with:
          python-version: ${{ matrix.python-version }}
