name: build

on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.11", "3.10" ]
        poetry-version: [ "1.7.1", "1.8.3" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch all tags
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
          python-version: ${{ matrix.python-version }}

    - name: Run image
      uses: abatilo/actions-poetry@v3
      with:
          poetry-version: ${{ matrix.poetry-version }}

    - name: Install build dependencies
      run: poetry install

    - name: Build
      run: poetry build
